version: '2'

services:
  backend:
    build: .
    ports:
      - "10503:50503"
    command: gunicorn example_reporting_web_services.app_ws:app --bind 0.0.0.0:50503 -w 1 -k uvicorn.workers.UvicornWorker
    
