version: 2.1
orbs:
  python: circleci/python@0.2.1
jobs:
  mybuild:
    environment:
      IMAGE_NAME: sarramagna/example_reporting_web_services
    docker:
      - image: 'circleci/buildpack-deps:stretch'
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: 'docker build -t $IMAGE_NAME:latest .'
  mytest:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: mkdir -p /home/circleci/logs/
          name: create log dir
      - run:
          command: python -m unittest discover -s tests -p 'test_*.py'
          name: unit tests
workflows:
  build-master:
    jobs:
      - mybuild:
          filters:
            branches:
              only: main
      - mytest

